AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda

Resources:
  # Define API Gateway
  FastAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        InvokeRole: NONE # Disable IAM authentication if not needed

  # Define Lambda function
  FastAPILambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.handler
      Runtime: python3.10
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FastAPIGateway # Explicitly link to API Gateway
            Path: /{proxy+}
            Method: ANY
