AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Telegram Bot Webhook Serverless Deployment

Globals:
  Function:
    Timeout: 180
    MemorySize: 256

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TelegramBotLambda
      Handler: bot.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          AUTHORIZED_USERS: !Ref AuthorizedUsers
          OPENAI_API_KEY: !Ref OpenAiApiKey
          GPT_MODEL: !Ref GPTModel
          GPT_SYSTEM_PROMPT: !Ref GPTSystemPrompt
          DEPLOYMENT_REGION: !Sub "${AWS::Region}"
          TASK_MANAGER_API_GATEWAY_URL: !Ref TaskManagerAPIGatewayURL
      Events:
        ApiWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

Parameters:
  TelegramBotToken:
    Type: String
    Description: "Telegram Bot API Token"

  AuthorizedUsers:
    Type: String
    Description: "Comma-separated list of authorized user IDs"

  OpenAiApiKey:
    Type: String
    Description: "OpenAI API token"

  GPTModel:
    Type: String
    Default: "gpt-4o"
    Description: "GPT Model"

  GPTSystemPrompt:
    Type: String
    Default: "You are a helpful assistant that helps users manage their tasks."
    Description: "GPT System Prompt"

  TaskManagerAPIGatewayURL:
    Type: String
    Default: "Your API Gateway URL here."
    Description: "Task Manager API Gateway URL"

Outputs:
  BotApiEndpoint:
    Description: "API Gateway endpoint for Telegram Webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"
